### PR TITLE
MemberCount: add thread support

### LINKED ISSUE #2379: [Bug] MemberCount showing 0 online members while viewing threads
### Discord Account

fairwellnoob

### What happens when the bug or crash occurs?

The members online in the channel is 0

### What is the expected behaviour?

The members online in the channel should be listed correctly (in this case, it should be 5 online)

### How do you recreate this bug or crash?

I have honestly no idea. Some servers have this, some don't. I've tried creating a forum channel in my own server while it was community, disabling community, going back into the forum channel, and now it's working. But when I go to another server, all of a sudden it doesn't work anymore.
Screenshot_2
Screenshot_1

### Errors

[discord.com-1713874622997.log](https://github.com/Vendicated/Vencord/files/15076677/discord.com-1713874622997.log)
[discord.com-1713874619273.log](https://github.com/Vendicated/Vencord/files/15076680/discord.com-1713874619273.log)
[discord.com-1713874616051.log](https://github.com/Vendicated/Vencord/files/15076681/discord.com-1713874616051.log)
[discord.com-1713874612258.log](https://github.com/Vendicated/Vencord/files/15076682/discord.com-1713874612258.log)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

### PR DESCRIPTION
**Pull request by ImBonana**
fix #2379

### CODE REVIEW

File: src/plugins/memberCount/MemberCount.tsx [hunk 1]
```diff
@@ -30,10 +30,19 @@ export function MemberCount({ isTooltip, tooltipGuildId }: { isTooltip?: true; t
         () => ChannelMemberStore.getProps(guildId, currentChannel?.id)
     );
 
+    const threads = useStateFromStores(
```
Comment (Vendicated) [inline src/plugins/memberCount/MemberCount.tsx:33]:
```suggestion
    const threadGroups = useStateFromStores(
```

File: src/plugins/memberCount/MemberCount.tsx [hunk 2]
```diff
@@ -30,10 +30,19 @@ export function MemberCount({ isTooltip, tooltipGuildId }: { isTooltip?: true; t
...
+        [ThreadMemberListStore],
+        () => ThreadMemberListStore.getMemberListSections(currentChannel.id)
+    );
+
     if (!isTooltip && (groups.length >= 1 || groups[0].id !== "unknown")) {
         onlineCount = groups.reduce((total, curr) => total + (curr.id === "offline" ? 0 : curr.count), 0);
     }
 
+    if (!isTooltip && threads && (Object.values(threads).length >= 1)) {
```
Comment (Vendicated) [inline src/plugins/memberCount/MemberCount.tsx:42]:
```suggestion
    if (!isTooltip && threads && !isObjectEmpty(threads)) {
```

**Review by Vendicated — COMMENTED** [review]
thank you for the fix, looks good for the most part!

**Comment by Vendicated** [comment]
thank you
