### PR TITLE
MessageClickActions: allow deleting one's own user app messages

### LINKED ISSUE #3805: [Bug] messageClickActions delete sequence not working for user apps
### What happens when the bug or crash occurs?

The message does not get deleted

### What is the expected behaviour?

I expect that when a backspace click a message i sent (or invoked by me through a chat input command provided by a user app) that it should be deleted

### How do you recreate this bug or crash?

1. Install a user app
2. Run a command that invokes a response
3. Hold backspace and click

### Errors

_No response_

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [x] I am a Vencord Developer

### PR DESCRIPTION
**Pull request by nin0-dev**
closes #3805

### CODE REVIEW

**Comment by nin0-dev** [comment]
i feel like the type should also be updated to include interaction meta instead of `any`ing the message

**Comment by Vendicated** [comment]
yes, update the type instead of casting to any

**Comment by nin0-dev** [comment]
@Copilot review

File: packages/discord-types/src/common/messages/Message.d.ts [hunk 1]
```diff
@@ -71,6 +71,21 @@ export class Message extends DiscordRecord {
...
     }[];
+    interactionMetadata?: {
+        id: string;
+        type: number;
+        name?: string;
+        command_type?: number;
+        ephemerality_reason?: number;
+        user: User;
+        authorizing_integration_owners: {
+            [key: number]: string;
```
Comment (Vendicated) [inline packages/discord-types/src/common/messages/Message.d.ts]:
```suggestion
            [key: ApplicationIntegrationType]: string;
```

and add enum

File: src/plugins/messageClickActions/index.ts [hunk 2]
```diff
@@ -77,6 +77,10 @@ export default definePlugin({
 
     onMessageClick(msg, channel, event) {
         const isMe = msg.author.id === UserStore.getCurrentUser().id;
+        const isSelfInvokedUserApp = msg.interactionMetadata ? (() => {
+            if (msg.interactionMetadata.authorizing_integration_owners[0]) return false;
+            else return msg.interactionMetadata.authorizing_integration_owners[1] === UserStore.getCurrentUser().id;
+        })() : false;
```
Comment (Vendicated) [inline src/plugins/messageClickActions/index.ts]:
```suggestion
        const myId = AuthenticationStore.getId();
        const isMe = msg.author.id === myId;
        const isSelfInvokedUserApp = msg.interactionMetadata?.authorizing_integration_owners[ApplicationIntegrationType.USER_INSTALL]) === myId;
```

**Comment by nin0-dev** [comment]
@Codium-AI-Agent /review

**Comment by justjxke** [comment]
@codex get in on this bro
