### PR TITLE
fix(RoleColorEverywhere): MessageLinkEmbeds DM error

### LINKED ISSUE #646: [Bug] message link embeds from dms not working
### Discord Account

GracefulLion#9559

### What happens when the bug or crash occurs?

When I try to send a message link of a dm, I get an error (pictured below) within dms or in a server

image

### What is the expected behaviour?

I expect an embed preview like how it works when sending a message link in a server:
image

If the message isn't available for any reason (ex. I can't see this DM or I'm not in the server, I expect no preview). 

### How do you recreate this bug or crash?

1. select copy message link of a dm in context menu
2. send this message link in a dm or server
3. error occurs 

### Errors

```js
4b9659d7526aa3979710.js:8922  Vencord   React ErrorBoundary  Component Stack 
  at n (https://discord.com/assets/4b9659d7526aa3979710.js:2655:489)
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:2667:136)
    at J (WebpackModule837054:2:7657)
    at span
    at m (https://discord.com/assets/4b9659d7526aa3979710.js:2748:122)
    at span
    at div
    at div
    at div
    at article
    at t (https://discord.com/assets/975aba216feae213687f.js:11:243)
    at Oy (VencordRenderer:50:23330)
    at Fy (VencordRenderer:50:22724)
    at <anonymous> (VencordRenderer:14:793)
    at div
    at a (WebpackModule643916:2:112863)
    at gs (WebpackModule643916:2:122330)
    at div
    at U (https://discord.com/assets/4b9659d7526aa3979710.js:9589:854)
    at h (https://discord.com/assets/6711a2d181d475a23422.js:27:120)
    at li
    at U (https://discord.com/assets/4b9659d7526aa3979710.js:9589:854)
    at $n (WebpackModule259135:2:35602)
    at ol
    at div
    at D (https://discord.com/assets/4b9659d7526aa3979710.js:9589:257)
    at div
    at eval (WebpackModule707961:2:137899)
    at div
    at g (https://discord.com/assets/4b9659d7526aa3979710.js:8563:479)
    at Ol (WebpackModule259135:2:122208)
    at eval (WebpackModule259135:2:127674)
    at u (https://discord.com/assets/4b9659d7526aa3979710.js:2615:292)
    at main
    at Sn (https://discord.com/assets/79226e60c979f811ea95.js:189:427)
    at https://discord.com/assets/79226e60c979f811ea95.js:2438:276
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:2619:982)
    at ChatLayerProvider
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:2457:337)
    at n (https://discord.com/assets/79226e60c979f811ea95.js:197:27)
    at https://discord.com/assets/79226e60c979f811ea95.js:202:813
    at div
    at div
    at o (WebpackModule292003:2:119551)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1499:594)
    at https://discord.com/assets/4b9659d7526aa3979710.js:2567:856
    at eval (WebpackModule292003:2:133006)
    at qoe (WebpackModule409169:2:1203983)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1771:221)
    at c (https://discord.com/assets/4b9659d7526aa3979710.js:4720:585)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1772:166)
    at div
    at div
    at div
    at lie (WebpackModule409169:2:1206893)
    at div
    at l (https://discord.com/assets/4b9659d7526aa3979710.js:342:570)
    at n (WebpackModule409169:2:1240154)
    at div
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:9307:79)
    at n (WebpackModule409169:2:1242570)
    at Yae (WebpackModule409169:2:1243637)
    at div
    at n (WebpackModule707961:2:161608)
    at Kae (WebpackModule409169:2:1243957)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1771:221)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1772:166)
    at i (WebpackModule409169:2:1289387)
    at Suspense
    at f
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1771:221)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1772:166)
    at div
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:2619:982)
    at VerificationLayerProvider
    at Pe (https://discord.com/assets/4b9659d7526aa3979710.js:2347:189)
    at div
    at div
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:2619:982)
    at AppLayerProvider
    at p (https://discord.com/assets/4b9659d7526aa3979710.js:4560:769)
    at D (https://discord.com/assets/4b9659d7526aa3979710.js:9589:257)
    at n (WebpackModule443269:2:4653)
    at T (https://discord.com/assets/4b9659d7526aa3979710.js:2378:812)
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:2379:542)
    at a (https://discord.com/assets/4b9659d7526aa3979710.js:8789:277)
    at p (https://discord.com/assets/4b9659d7526aa3979710.js:2334:239)
    at zt (https://discord.com/assets/4b9659d7526aa3979710.js:2361:492)
    at n (https://discord.com/assets/4b9659d7526aa3979710.js:3006:27)
    at a (https://discord.com/assets/4b9659d7526aa3979710.js:8788:301)
    at https://discord.com/assets/4b9659d7526aa3979710.js:2537:942
    at cn (https://discord.com/assets/4b9659d7526aa3979710.js:2546:248)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1768:520)
    at t (https://discord.com/assets/4b9659d7526aa3979710.js:1725:436)
    at Ar (https://discord.com/assets/4b9659d7526aa3979710.js:3043:523)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

Other client information:
image

### PR DESCRIPTION
**Pull request by lewisakura**
Adds null checks for both channel and guild ID, and short circuits both of them being undefined when getting a color.

Fixes #646.

### CODE REVIEW

File: src/plugins/roleColorEverywhere.tsx [hunk 1]
```diff
@@ -96,6 +96,7 @@ export default definePlugin({
     settings,
 
     getColor(userId: string, { channelId, guildId }: { channelId?: string; guildId?: string; }) {
+        if (!guildId && !channelId) return null;
```
Comment (Vendicated) [inline src/plugins/roleColorEverywhere.tsx:99]: this isn't even needed, the line below already covers it

**Review by 3kh0 — APPROVED** [review]

**Review by Nuckyz — APPROVED** [review]
