### PR TITLE
PinDMs: Fix unexpected behaviours when using last message sort

### LINKED ISSUE #2322: [Bug] PinDMs: alt up/down doesn't work correctly when using recent message sort order
### Discord Account

_No response_

### What happens when the bug or crash occurs?

It just doesn't navigate in the correct order

### What is the expected behaviour?

It should have the correct order

### How do you recreate this bug or crash?

1. Set sort order to recent message
2. Pin a few dms
3. Have bottom pin message you so it goes to top
4. Try using keyboard navigation
5. Observe that it doesn't behave correctly

### Errors

_No response_

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

### PR DESCRIPTION
**Pull request by puppy-girl**
Fixed alt + up/down not working as expected and fixed the channel preview when collapsing a category being incorrect when using the most recent message sort option

Resolves #2322

### CODE REVIEW

**Comment by Vendicated** [comment]
cc @Syncxv

File: src/plugins/pinDms/data.ts [hunk 1]
```diff
@@ -106,7 +106,12 @@ export function categoryLen() {
 }
 
 export function getAllUncollapsedChannels() {
-    return categories.filter(c => !c.collapsed).map(c => c.channels).flat();
+    return categories.filter(c => !c.collapsed).map(c => {
```
Comment (Vendicated) [inline src/plugins/pinDms/data.ts:109]: i know this was already this way before your changes, but `.map(...).flat()` is better written as `.flatMap(...)`
```suggestion
    return categories.filter(c => !c.collapsed).flatMap(c => {
```

**Comment by Nuckyz** [comment]
Thanks for the fix! But in the next time please don't pr from main as it makes it harder to checkout your pr and test.
