### PR TITLE
Fix(InvisibleChat) Fix chatbar icon patch (closes #560)

### LINKED ISSUE #560: [Bug] Invisible Chat not working
### Discord Account

Tami#7071

### What happens when the bug or crash occurs?

There is no Invisible Chat Icon to use (and the plugin has no other options than setting a password so it is enabled)

### What is the expected behaviour?

Show the Invisible Chat icon ^^

### How do you recreate this bug or crash?

1. Install Vencord
2. Enable Invisible Chat
3. No Button

### Errors

```
No crash
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

### PR DESCRIPTION
**Pull request by SammCheese**

### CODE REVIEW

File: src/plugins/invisibleChat/index.tsx [hunk 1]
```diff
@@ -131,8 +131,8 @@ export default definePlugin({
         {
             find: ".activeCommandOption",
             replacement: {
-                match: /.=.\.activeCommand,.=.\.activeCommandOption,.{1,133}(.)=\[\];/,
-                replace: "$&;$1.push($self.chatBarIcon());",
+                match: /(.)\.push.{1,50}\(.{1,3},\{.{1,30}\},"gift"\)\)/,
```
Comment (Vendicated) [inline src/plugins/invisibleChat/index.tsx:134]:
```suggestion
                match: /(.)\.push.{1,50}\(\i,\{.{1,30}\},"gift"\)\)/,
```
