### PR TITLE
BetterSettings: fix "Disable Fade" feature

### LINKED ISSUE #3970: [Bug] "Disable Fade" option in "BetterSettings" is broken
### Content

opening/closing discord settings still has a animation despite having "Disable Fade" enabled in the "BetterSettings" plugin

### Request Agreement

- [x] I have read the requirements for opening an issue above

### PR DESCRIPTION
**Pull request by KITFC-dev**
This change resolves #3970 by removing fade animations of settings menu modal

### CODE REVIEW

File: src/plugins/betterSettings/index.tsx [hunk 1]
```diff
@@ -126,6 +126,28 @@ export default definePlugin({
             ],
             predicate: () => settings.store.disableFade
         },
+        { // Disable fade animations for settings menu
+            find: "layer-modal",
+            replacement: [
+                {
+                    match: /(\i)\.animated\.div,\{"data-mana-component":"layer-modal"/,
+                    replace: '"div",{"data-mana-component":"layer-modal"'
```
Comment (Vendicated) [inline src/plugins/betterSettings/index.tsx]:
```suggestion
                    match: /(\i)\.animated\.div(?=,\{"data-mana-component":"layer-modal")/,
                    replace: '"div"'
```

File: src/plugins/betterSettings/index.tsx [hunk 2]
```diff
@@ -126,6 +126,28 @@ export default definePlugin({
...
+                },
+                {
+                    match: /("data-mana-component":"layer-modal"[^}]*?)style:(\i),/,
+                    replace: "$1style:{},"
```
Comment (Vendicated) [inline src/plugins/betterSettings/index.tsx]:
```suggestion
                    match: /(?<="data-mana-component":"layer-modal"[^}]*?)style:\i,/,
                    replace: "style:{},"
```

File: src/plugins/betterSettings/index.tsx [hunk 3]
```diff
@@ -126,6 +126,28 @@ export default definePlugin({
...
+                }
+            ],
+            predicate: () => settings.store.disableFade
+        },
+        { // Disable initial and exit delay for settings menu
```
Comment (Vendicated) [inline src/plugins/betterSettings/index.tsx:143]:
```suggestion
		// Disable initial and exit delay for settings menu
        {
```

Comment (Vendicated) [reply src/plugins/betterSettings/index.tsx:143]: Oh god the entire file uses this formatting, welp D:
